apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgo-ingress
  namespace: ha-proxy
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  # tls:
  
  #   secretName: adria-pg-db-pgbouncer
  rules:
  - http:
      paths:
      - path: /pgbouncer
        pathType: Prefix
        backend:
          service:
            name: pgo-ha/adria-pg-db-pgbouncer 
            port:
              number: 5432

  tls: 
    - secretName: pgo-ha/adria-pg-db-pgbouncer 
      # - path: /grafana
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: crunchy-grafana   
      #       port:
      #         number: 3000
