apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgo-ingress-v1
  namespace: pgo-ha
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - http:
      paths:
      - path: /pgbouncer
        pathType: Prefix
        backend:
          service:
            name: adria-pg-db-pgbouncer  #  service name
            port:
              number: 5432
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path : /grafana 
        pathType: Prefix 
        backend: 
          service: 
            name: crunchy-grafana
            port: 
              number: 3000
      - path : /prom 
        pathType: Prefix 
        backend: 
          service: 
            name: crunchy-prometheus 
            port: 
              number: 9090



  tls: 
    - secretName: adria-pg-db-cluster-cert  #  secret name
