apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgo-ha
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  tls:
  
    secretName: adria-pg-db-pgbouncer
  rules:
  - http:
      paths:
      - path: /pgbouncer
        pathType: Prefix
        backend:
          service:
            name: adria-pg-db-pgbouncer 
            port:
              number: 5432
---
#crunchy-grafana   
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ha
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:

  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: crunchy-grafana   
            port:
              number: 3000