apiVersion: v1
kind: ConfigMap
metadata:
  name: adria-init-sql
  namespace: pgo-ha
data:
  init.sql: |
    GRANT CONNECT ON DATABASE adriadb TO test;
    GRANT USAGE ON SCHEMA public TO test;
    GRANT CREATE ON SCHEMA public TO test;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO test;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO test;
    GRANT USAGE, SELECT ON SEQUENCE item_seq TO test;
