---
- name: Configure Kubernetes Master Nodes
  hosts: [kubemasters]
  become: yes
  roles:
  - role: 'k8s_master'

- name: Configure Kubernetes Worker Nodes
  hosts: [kubeworkers]
  become: yes
  roles:
  - role: 'k8s_worker'


