apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: pgo-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool
        envFrom:
        - configMapRef:
            name: pgpool-config
        volumeMounts:
        - name: pgpool-config
          mountPath: /usr/local/pgpool-II/etc
        env:
        # - name: PGPOOL_PARAMS_BACKEND_HOSTNAME0
        #   value: "adria-pg-db-primary"
        # - name: PGPOOL_PARAMS_BACKEND_HOSTNAME1
        #   value: "adria-pg-db-replicas"
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: adria-pg-db-pguser-mohamed
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adria-pg-db-pguser-mohamed
              key: password
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
  namespace: pgo-ha
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 9999
    targetPort: 9999
